name: with_run_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter_dotenv: ^5.0.2

  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
 
  google_sign_in: ^6.3.0

  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0  # 위치 권한 및 현재 위치 얻기
  geocoding: ^3.0.0
 
  provider: ^6.1.4
  http: ^1.2.2
  intl: ^0.20.2

  image_picker: ^1.1.2
  time_range_picker: ^2.3.0
  permission_handler: ^12.0.0+1
  pedometer: ^4.1.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - assets/icons/
    - assets/lottie/


